name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          # Macos
          - runs-on: macOS-latest
            target: x86_64-apple-darwin
          - runs-on: macOS-latest
            target: aarch64-apple-darwin
          # Windows
          - runs-on: windows-latest
            target: x86_64-pc-windows-gnu
#          - runs-on: windows-latest
#            target: i686-pc-windows-gnu
          # Linux GNU
          - runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
          - runs-on: ubuntu-24.04
            target: armv7-unknown-linux-gnueabihf
          - runs-on: ubuntu-24.04
            target: i686-unknown-linux-gnu
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          # Linux MUSL
          - runs-on: ubuntu-24.04
            target: armv7-unknown-linux-musleabihf
          - runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
          - runs-on: ubuntu-24.04
            target: i686-unknown-linux-musl
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}-release
          path: target/*/release/rust-cross-compilation*